### ISSUE TITLE
Run it locally or in Aws ?

### ISSUE THREAD

**Issue by tukangcode** [nanoskript/deepcreampy-onnx-docker#1]
Hi ! can i run this locally on my machine or host it on aws ? are this can be run instanly after clone or need api from your site ?

**Comment by nanoskript** [comment]
You can run this model by installing Docker (on a server or locally) and running the command in the README. The API will be available under `http://localhost:PORT`.

**Comment by tukangcode** [comment]
ok thanks i close the issue
