### ISSUE TITLE
Black Bar uncensored not work (format png image)

### ISSUE THREAD

**Issue by tukangcode** [nanoskript/deepcreampy-onnx-docker#2]
How reproduce 

- Source image download from sauce site.
- Source Image are edited every black bar and green it
- export it as PNG
- Upload to site
- Execute proceed
- Post result show same image as the censored one

**Comment by nanoskript** [comment]
I can't reproduce this. The mask color must be exactly and entirely `(0, 255, 0)`. There are further details on DeepCreamPy's page: https://github.com/Deepshift/DeepCreamPy/blob/master/docs/TROUBLESHOOTING_DECENSORS.md

**Comment by tukangcode** [comment]
ok i close the issue.
